language: python
sudo: required
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
install:
  - pip install -r requirements.txt
  - pip install .

script:
  - python -m unittest discover tests/
